// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/packet_components/objective/v1/objective.proto (package spawner.packet_components.objective.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/packet_components/objective/v1/objective.proto.
 */
export const file_spawner_packet_components_objective_v1_objective: GenFile = /*@__PURE__*/
  fileDesc("CjZzcGF3bmVyL3BhY2tldF9jb21wb25lbnRzL29iamVjdGl2ZS92MS9vYmplY3RpdmUucHJvdG8SJnNwYXduZXIucGFja2V0X2NvbXBvbmVudHMub2JqZWN0aXZlLnYxIjYKE09iamVjdGl2ZUV2ZW50U3RhcnQSCgoCaWQYASABKAkSEwoLZGVzY3JpcHRpb24YAiABKAkiHwoRT2JqZWN0aXZlRXZlbnRFbmQSCgoCaWQYASABKAki/QEKDk9iamVjdGl2ZUV2ZW50EkgKBHR5cGUYASABKA4yOi5zcGF3bmVyLnBhY2tldF9jb21wb25lbnRzLm9iamVjdGl2ZS52MS5PYmplY3RpdmVFdmVudFR5cGUSTAoFc3RhcnQYAiABKAsyOy5zcGF3bmVyLnBhY2tldF9jb21wb25lbnRzLm9iamVjdGl2ZS52MS5PYmplY3RpdmVFdmVudFN0YXJ0SAASSAoDZW5kGAMgASgLMjkuc3Bhd25lci5wYWNrZXRfY29tcG9uZW50cy5vYmplY3RpdmUudjEuT2JqZWN0aXZlRXZlbnRFbmRIAEIJCgdwYXlsb2FkKngKEk9iamVjdGl2ZUV2ZW50VHlwZRIkCiBPQkpFQ1RJVkVfRVZFTlRfVFlQRV9VTlNQRUNJRklFRBAAEh4KGk9CSkVDVElWRV9FVkVOVF9UWVBFX1NUQVJUEAESHAoYT0JKRUNUSVZFX0VWRU5UX1RZUEVfRU5EEAJC8wEKKmNvbS5zcGF3bmVyLnBhY2tldF9jb21wb25lbnRzLm9iamVjdGl2ZS52MUIOT2JqZWN0aXZlUHJvdG9QAaICA1NQT6oCJVNwYXduZXIuUGFja2V0Q29tcG9uZW50cy5PYmplY3RpdmUuVjHKAiVTcGF3bmVyXFBhY2tldENvbXBvbmVudHNcT2JqZWN0aXZlXFYx4gIxU3Bhd25lclxQYWNrZXRDb21wb25lbnRzXE9iamVjdGl2ZVxWMVxHUEJNZXRhZGF0YeoCKFNwYXduZXI6OlBhY2tldENvbXBvbmVudHM6Ok9iamVjdGl2ZTo6VjFiBnByb3RvMw");

/**
 * @generated from message spawner.packet_components.objective.v1.ObjectiveEventStart
 */
export type ObjectiveEventStart = Message<"spawner.packet_components.objective.v1.ObjectiveEventStart"> & {
  /**
   * Indicates the identifier of the objective. If the client passes a value,
   * the passed value will be used instead of auto-generated identifier.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The objective of the agent. Clients may pass a value to manually set an
   * objective.
   *
   * @generated from field: string description = 2;
   */
  description: string;
};

/**
 * Describes the message spawner.packet_components.objective.v1.ObjectiveEventStart.
 * Use `create(ObjectiveEventStartSchema)` to create a new message.
 */
export const ObjectiveEventStartSchema: GenMessage<ObjectiveEventStart> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_objective_v1_objective, 0);

/**
 * @generated from message spawner.packet_components.objective.v1.ObjectiveEventEnd
 */
export type ObjectiveEventEnd = Message<"spawner.packet_components.objective.v1.ObjectiveEventEnd"> & {
  /**
   * Indicates the identifier of the objective. The client may pass a value to
   * end a specific objective.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message spawner.packet_components.objective.v1.ObjectiveEventEnd.
 * Use `create(ObjectiveEventEndSchema)` to create a new message.
 */
export const ObjectiveEventEndSchema: GenMessage<ObjectiveEventEnd> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_objective_v1_objective, 1);

/**
 * @generated from message spawner.packet_components.objective.v1.ObjectiveEvent
 */
export type ObjectiveEvent = Message<"spawner.packet_components.objective.v1.ObjectiveEvent"> & {
  /**
   * @generated from field: spawner.packet_components.objective.v1.ObjectiveEventType type = 1;
   */
  type: ObjectiveEventType;

  /**
   * @generated from oneof spawner.packet_components.objective.v1.ObjectiveEvent.payload
   */
  payload: {
    /**
     * @generated from field: spawner.packet_components.objective.v1.ObjectiveEventStart start = 2;
     */
    value: ObjectiveEventStart;
    case: "start";
  } | {
    /**
     * @generated from field: spawner.packet_components.objective.v1.ObjectiveEventEnd end = 3;
     */
    value: ObjectiveEventEnd;
    case: "end";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message spawner.packet_components.objective.v1.ObjectiveEvent.
 * Use `create(ObjectiveEventSchema)` to create a new message.
 */
export const ObjectiveEventSchema: GenMessage<ObjectiveEvent> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_objective_v1_objective, 2);

/**
 * @generated from enum spawner.packet_components.objective.v1.ObjectiveEventType
 */
export enum ObjectiveEventType {
  /**
   * @generated from enum value: OBJECTIVE_EVENT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Set an objective for the agent to pursue.
   *
   * @generated from enum value: OBJECTIVE_EVENT_TYPE_START = 1;
   */
  START = 1,

  /**
   * Represents the end an objective. This may also be used to force-end the
   * objective by requesting from the client.
   *
   * @generated from enum value: OBJECTIVE_EVENT_TYPE_END = 2;
   */
  END = 2,
}

/**
 * Describes the enum spawner.packet_components.objective.v1.ObjectiveEventType.
 */
export const ObjectiveEventTypeSchema: GenEnum<ObjectiveEventType> = /*@__PURE__*/
  enumDesc(file_spawner_packet_components_objective_v1_objective, 0);

