// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/error/v1/error.proto (package spawner.error.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/error/v1/error.proto.
 */
export const file_spawner_error_v1_error: GenFile = /*@__PURE__*/
  fileDesc("ChxzcGF3bmVyL2Vycm9yL3YxL2Vycm9yLnByb3RvEhBzcGF3bmVyLmVycm9yLnYxIkkKCkVycm9yRXZlbnQSKgoEY29kZRgBIAEoDjIcLnNwYXduZXIuZXJyb3IudjEuU3RhdHVzQ29kZRIPCgdtZXNzYWdlGAIgASgJKqYECgpTdGF0dXNDb2RlEhsKF1NUQVRVU19DT0RFX1VOU1BFQ0lGSUVEEAASEgoOU1RBVFVTX0NPREVfT0sQARIZChVTVEFUVVNfQ09ERV9DQU5DRUxMRUQQAhIXChNTVEFUVVNfQ09ERV9VTktOT1dOEAMSIAocU1RBVFVTX0NPREVfSU5WQUxJRF9BUkdVTUVOVBAEEiEKHVNUQVRVU19DT0RFX0RFQURMSU5FX0VYQ0VFREVEEAUSGQoVU1RBVFVTX0NPREVfTk9UX0ZPVU5EEAYSHgoaU1RBVFVTX0NPREVfQUxSRUFEWV9FWElTVFMQBxIhCh1TVEFUVVNfQ09ERV9QRVJNSVNTSU9OX0RFTklFRBAIEiIKHlNUQVRVU19DT0RFX1JFU09VUkNFX0VYSEFVU1RFRBAJEiMKH1NUQVRVU19DT0RFX0ZBSUxFRF9QUkVDT05ESVRJT04QChIXChNTVEFUVVNfQ09ERV9BQk9SVEVEEAsSHAoYU1RBVFVTX0NPREVfT1VUX09GX1JBTkdFEAwSHQoZU1RBVFVTX0NPREVfVU5JTVBMRU1FTlRFRBANEhgKFFNUQVRVU19DT0RFX0lOVEVSTkFMEA4SGwoXU1RBVFVTX0NPREVfVU5BVkFJTEFCTEUQDxIZChVTVEFUVVNfQ09ERV9EQVRBX0xPU1MQEBIfChtTVEFUVVNfQ09ERV9VTkFVVEhFTlRJQ0FURUQQEUKGAQoUY29tLnNwYXduZXIuZXJyb3IudjFCCkVycm9yUHJvdG9QAaICA1NFWKoCEFNwYXduZXIuRXJyb3IuVjHKAhFTcGF3bmVyXEVycm9yX1xWMeICHVNwYXduZXJcRXJyb3JfXFYxXEdQQk1ldGFkYXRh6gISU3Bhd25lcjo6RXJyb3I6OlYxYgZwcm90bzM");

/**
 * Indicates and provides information on errors.
 *
 * @generated from message spawner.error.v1.ErrorEvent
 */
export type ErrorEvent = Message<"spawner.error.v1.ErrorEvent"> & {
  /**
   * Output only.
   *
   * @generated from field: spawner.error.v1.StatusCode code = 1;
   */
  code: StatusCode;

  /**
   * Output only. A developer-facing message, in English.
   *
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message spawner.error.v1.ErrorEvent.
 * Use `create(ErrorEventSchema)` to create a new message.
 */
export const ErrorEventSchema: GenMessage<ErrorEvent> = /*@__PURE__*/
  messageDesc(file_spawner_error_v1_error, 0);

/**
 * @generated from enum spawner.error.v1.StatusCode
 */
export enum StatusCode {
  /**
   * @generated from enum value: STATUS_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATUS_CODE_OK = 1;
   */
  OK = 1,

  /**
   * @generated from enum value: STATUS_CODE_CANCELLED = 2;
   */
  CANCELLED = 2,

  /**
   * @generated from enum value: STATUS_CODE_UNKNOWN = 3;
   */
  UNKNOWN = 3,

  /**
   * @generated from enum value: STATUS_CODE_INVALID_ARGUMENT = 4;
   */
  INVALID_ARGUMENT = 4,

  /**
   * @generated from enum value: STATUS_CODE_DEADLINE_EXCEEDED = 5;
   */
  DEADLINE_EXCEEDED = 5,

  /**
   * @generated from enum value: STATUS_CODE_NOT_FOUND = 6;
   */
  NOT_FOUND = 6,

  /**
   * @generated from enum value: STATUS_CODE_ALREADY_EXISTS = 7;
   */
  ALREADY_EXISTS = 7,

  /**
   * @generated from enum value: STATUS_CODE_PERMISSION_DENIED = 8;
   */
  PERMISSION_DENIED = 8,

  /**
   * @generated from enum value: STATUS_CODE_RESOURCE_EXHAUSTED = 9;
   */
  RESOURCE_EXHAUSTED = 9,

  /**
   * @generated from enum value: STATUS_CODE_FAILED_PRECONDITION = 10;
   */
  FAILED_PRECONDITION = 10,

  /**
   * @generated from enum value: STATUS_CODE_ABORTED = 11;
   */
  ABORTED = 11,

  /**
   * @generated from enum value: STATUS_CODE_OUT_OF_RANGE = 12;
   */
  OUT_OF_RANGE = 12,

  /**
   * @generated from enum value: STATUS_CODE_UNIMPLEMENTED = 13;
   */
  UNIMPLEMENTED = 13,

  /**
   * @generated from enum value: STATUS_CODE_INTERNAL = 14;
   */
  INTERNAL = 14,

  /**
   * @generated from enum value: STATUS_CODE_UNAVAILABLE = 15;
   */
  UNAVAILABLE = 15,

  /**
   * @generated from enum value: STATUS_CODE_DATA_LOSS = 16;
   */
  DATA_LOSS = 16,

  /**
   * @generated from enum value: STATUS_CODE_UNAUTHENTICATED = 17;
   */
  UNAUTHENTICATED = 17,
}

/**
 * Describes the enum spawner.error.v1.StatusCode.
 */
export const StatusCodeSchema: GenEnum<StatusCode> = /*@__PURE__*/
  enumDesc(file_spawner_error_v1_error, 0);

