// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/routing/v1/routing.proto (package spawner.routing.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/routing/v1/routing.proto.
 */
export const file_spawner_routing_v1_routing: GenFile = /*@__PURE__*/
  fileDesc("CiBzcGF3bmVyL3JvdXRpbmcvdjEvcm91dGluZy5wcm90bxISc3Bhd25lci5yb3V0aW5nLnYxIi8KC0V2ZW50UGxheWVyEgoKAmlkGAEgASgJEhQKDGRpc3BsYXlfbmFtZRgCIAEoCSJFCg5FdmVudENoYXJhY3RlchIKCgJpZBgBIAEoCRIRCgljdXN0b21faWQYAiABKAkSFAoMZGlzcGxheV9uYW1lGAMgASgJIhgKCkV2ZW50QWdlbnQSCgoCaWQYASABKAki6gEKCkV2ZW50QWN0b3ISMAoEdHlwZRgBIAEoDjIiLnNwYXduZXIucm91dGluZy52MS5FdmVudEFjdG9yVHlwZRIxCgZwbGF5ZXIYAiABKAsyHy5zcGF3bmVyLnJvdXRpbmcudjEuRXZlbnRQbGF5ZXJIABI7CgljaGFyYWN0ZXIYAyABKAsyIi5zcGF3bmVyLnJvdXRpbmcudjEuRXZlbnRDaGFyYWN0ZXJCAhgBSAASLwoFYWdlbnQYBCABKAsyHi5zcGF3bmVyLnJvdXRpbmcudjEuRXZlbnRBZ2VudEgAQgkKB3BheWxvYWQiaQoHUm91dGluZxIuCgZzb3VyY2UYASABKAsyHi5zcGF3bmVyLnJvdXRpbmcudjEuRXZlbnRBY3RvchIuCgZ0YXJnZXQYAiABKAsyHi5zcGF3bmVyLnJvdXRpbmcudjEuRXZlbnRBY3RvciqqAQoORXZlbnRBY3RvclR5cGUSIAocRVZFTlRfQUNUT1JfVFlQRV9VTlNQRUNJRklFRBAAEhsKF0VWRU5UX0FDVE9SX1RZUEVfUExBWUVSEAESIgoaRVZFTlRfQUNUT1JfVFlQRV9DSEFSQUNURVIQAhoCCAESGgoWRVZFTlRfQUNUT1JfVFlQRV9BR0VOVBADEhkKFUVWRU5UX0FDVE9SX1RZUEVfSEVSRRAEQpABChZjb20uc3Bhd25lci5yb3V0aW5nLnYxQgxSb3V0aW5nUHJvdG9QAaICA1NSWKoCElNwYXduZXIuUm91dGluZy5WMcoCElNwYXduZXJcUm91dGluZ1xWMeICHlNwYXduZXJcUm91dGluZ1xWMVxHUEJNZXRhZGF0YeoCFFNwYXduZXI6OlJvdXRpbmc6OlYxYgZwcm90bzM");

/**
 * @generated from message spawner.routing.v1.EventPlayer
 */
export type EventPlayer = Message<"spawner.routing.v1.EventPlayer"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Output only.
   *
   * @generated from field: string display_name = 2;
   */
  displayName: string;
};

/**
 * Describes the message spawner.routing.v1.EventPlayer.
 * Use `create(EventPlayerSchema)` to create a new message.
 */
export const EventPlayerSchema: GenMessage<EventPlayer> = /*@__PURE__*/
  messageDesc(file_spawner_routing_v1_routing, 0);

/**
 * @generated from message spawner.routing.v1.EventCharacter
 */
export type EventCharacter = Message<"spawner.routing.v1.EventCharacter"> & {
  /**
   * Output only.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string custom_id = 2;
   */
  customId: string;

  /**
   * Output only.
   *
   * @generated from field: string display_name = 3;
   */
  displayName: string;
};

/**
 * Describes the message spawner.routing.v1.EventCharacter.
 * Use `create(EventCharacterSchema)` to create a new message.
 */
export const EventCharacterSchema: GenMessage<EventCharacter> = /*@__PURE__*/
  messageDesc(file_spawner_routing_v1_routing, 1);

/**
 * @generated from message spawner.routing.v1.EventAgent
 */
export type EventAgent = Message<"spawner.routing.v1.EventAgent"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message spawner.routing.v1.EventAgent.
 * Use `create(EventAgentSchema)` to create a new message.
 */
export const EventAgentSchema: GenMessage<EventAgent> = /*@__PURE__*/
  messageDesc(file_spawner_routing_v1_routing, 2);

/**
 * @generated from message spawner.routing.v1.EventActor
 */
export type EventActor = Message<"spawner.routing.v1.EventActor"> & {
  /**
   * @generated from field: spawner.routing.v1.EventActorType type = 1;
   */
  type: EventActorType;

  /**
   * @generated from oneof spawner.routing.v1.EventActor.payload
   */
  payload: {
    /**
     * @generated from field: spawner.routing.v1.EventPlayer player = 2;
     */
    value: EventPlayer;
    case: "player";
  } | {
    /**
     * @generated from field: spawner.routing.v1.EventCharacter character = 3 [deprecated = true];
     * @deprecated
     */
    value: EventCharacter;
    case: "character";
  } | {
    /**
     * @generated from field: spawner.routing.v1.EventAgent agent = 4;
     */
    value: EventAgent;
    case: "agent";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message spawner.routing.v1.EventActor.
 * Use `create(EventActorSchema)` to create a new message.
 */
export const EventActorSchema: GenMessage<EventActor> = /*@__PURE__*/
  messageDesc(file_spawner_routing_v1_routing, 3);

/**
 * @generated from message spawner.routing.v1.Routing
 */
export type Routing = Message<"spawner.routing.v1.Routing"> & {
  /**
   * Source actor triggering the event. This is usually a player,
   * but may be an NPC for NPC-NPC events.
   *
   * @generated from field: spawner.routing.v1.EventActor source = 1;
   */
  source?: EventActor;

  /**
   * Target actor that responds to the input. This is usually a character.
   *
   * @generated from field: spawner.routing.v1.EventActor target = 2;
   */
  target?: EventActor;
};

/**
 * Describes the message spawner.routing.v1.Routing.
 * Use `create(RoutingSchema)` to create a new message.
 */
export const RoutingSchema: GenMessage<Routing> = /*@__PURE__*/
  messageDesc(file_spawner_routing_v1_routing, 4);

/**
 * @generated from enum spawner.routing.v1.EventActorType
 */
export enum EventActorType {
  /**
   * @generated from enum value: EVENT_ACTOR_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: EVENT_ACTOR_TYPE_PLAYER = 1;
   */
  PLAYER = 1,

  /**
   * @generated from enum value: EVENT_ACTOR_TYPE_CHARACTER = 2 [deprecated = true];
   * @deprecated
   */
  CHARACTER = 2,

  /**
   * @generated from enum value: EVENT_ACTOR_TYPE_AGENT = 3;
   */
  AGENT = 3,

  /**
   * Experimental. Only for event target field. Allows targeting
   * all actors in the interaction space.
   *
   * @generated from enum value: EVENT_ACTOR_TYPE_HERE = 4;
   */
  HERE = 4,
}

/**
 * Describes the enum spawner.routing.v1.EventActorType.
 */
export const EventActorTypeSchema: GenEnum<EventActorType> = /*@__PURE__*/
  enumDesc(file_spawner_routing_v1_routing, 0);

