// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/core_components/search/v1/search.proto (package spawner.core_components.search.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/core_components/search/v1/search.proto.
 */
export const file_spawner_core_components_search_v1_search: GenFile = /*@__PURE__*/
  fileDesc("Ci5zcGF3bmVyL2NvcmVfY29tcG9uZW50cy9zZWFyY2gvdjEvc2VhcmNoLnByb3RvEiFzcGF3bmVyLmNvcmVfY29tcG9uZW50cy5zZWFyY2gudjEiOwoRQ29yZVNlYXJjaEZlYXR1cmUSEQoJa25vd2xlZGdlGAEgASgIEhMKC29ic2VydmF0aW9uGAIgASgIIoEBChdDb3JlU2VhcmNoQ29uZmlndXJhdGlvbhJFCgdmZWF0dXJlGAEgASgLMjQuc3Bhd25lci5jb3JlX2NvbXBvbmVudHMuc2VhcmNoLnYxLkNvcmVTZWFyY2hGZWF0dXJlEhAKCGFnZW50X2lkGAIgASgJEg0KBXRvcF9rGAMgASgFIh8KD0NvcmVTZWFyY2hRdWVyeRIMCgR0ZXh0GAEgASgJImYKD0NvcmVTZWFyY2hNYXRjaBJFCgR0eXBlGAEgASgOMjcuc3Bhd25lci5jb3JlX2NvbXBvbmVudHMuc2VhcmNoLnYxLkNvcmVTZWFyY2hSZXN1bHRUeXBlEgwKBHRleHQYAiABKAkiVwoQQ29yZVNlYXJjaFJlc3VsdBJDCgdtYXRjaGVzGAEgAygLMjIuc3Bhd25lci5jb3JlX2NvbXBvbmVudHMuc2VhcmNoLnYxLkNvcmVTZWFyY2hNYXRjaCLqAQoKQ29yZVNlYXJjaBJRCg1jb25maWd1cmF0aW9uGAEgASgLMjouc3Bhd25lci5jb3JlX2NvbXBvbmVudHMuc2VhcmNoLnYxLkNvcmVTZWFyY2hDb25maWd1cmF0aW9uEkMKB3F1ZXJpZXMYAiADKAsyMi5zcGF3bmVyLmNvcmVfY29tcG9uZW50cy5zZWFyY2gudjEuQ29yZVNlYXJjaFF1ZXJ5EkQKB3Jlc3VsdHMYAyADKAsyMy5zcGF3bmVyLmNvcmVfY29tcG9uZW50cy5zZWFyY2gudjEuQ29yZVNlYXJjaFJlc3VsdCqPAQoUQ29yZVNlYXJjaFJlc3VsdFR5cGUSJwojQ09SRV9TRUFSQ0hfUkVTVUxUX1RZUEVfVU5TUEVDSUZJRUQQABIlCiFDT1JFX1NFQVJDSF9SRVNVTFRfVFlQRV9LTk9XTEVER0UQARInCiNDT1JFX1NFQVJDSF9SRVNVTFRfVFlQRV9PQlNFUlZBVElPThACQtcBCiVjb20uc3Bhd25lci5jb3JlX2NvbXBvbmVudHMuc2VhcmNoLnYxQgtTZWFyY2hQcm90b1ABogIDU0NTqgIgU3Bhd25lci5Db3JlQ29tcG9uZW50cy5TZWFyY2guVjHKAiBTcGF3bmVyXENvcmVDb21wb25lbnRzXFNlYXJjaFxWMeICLFNwYXduZXJcQ29yZUNvbXBvbmVudHNcU2VhcmNoXFYxXEdQQk1ldGFkYXRh6gIjU3Bhd25lcjo6Q29yZUNvbXBvbmVudHM6OlNlYXJjaDo6VjFiBnByb3RvMw");

/**
 * @generated from message spawner.core_components.search.v1.CoreSearchFeature
 */
export type CoreSearchFeature = Message<"spawner.core_components.search.v1.CoreSearchFeature"> & {
  /**
   * @generated from field: bool knowledge = 1;
   */
  knowledge: boolean;

  /**
   * @generated from field: bool observation = 2;
   */
  observation: boolean;
};

/**
 * Describes the message spawner.core_components.search.v1.CoreSearchFeature.
 * Use `create(CoreSearchFeatureSchema)` to create a new message.
 */
export const CoreSearchFeatureSchema: GenMessage<CoreSearchFeature> = /*@__PURE__*/
  messageDesc(file_spawner_core_components_search_v1_search, 0);

/**
 * @generated from message spawner.core_components.search.v1.CoreSearchConfiguration
 */
export type CoreSearchConfiguration = Message<"spawner.core_components.search.v1.CoreSearchConfiguration"> & {
  /**
   * Represents what to search over.
   *
   * @generated from field: spawner.core_components.search.v1.CoreSearchFeature feature = 1;
   */
  feature?: CoreSearchFeature;

  /**
   * @generated from field: string agent_id = 2;
   */
  agentId: string;

  /**
   * Get top_k results for each query.
   *
   * @generated from field: int32 top_k = 3;
   */
  topK: number;
};

/**
 * Describes the message spawner.core_components.search.v1.CoreSearchConfiguration.
 * Use `create(CoreSearchConfigurationSchema)` to create a new message.
 */
export const CoreSearchConfigurationSchema: GenMessage<CoreSearchConfiguration> = /*@__PURE__*/
  messageDesc(file_spawner_core_components_search_v1_search, 1);

/**
 * @generated from message spawner.core_components.search.v1.CoreSearchQuery
 */
export type CoreSearchQuery = Message<"spawner.core_components.search.v1.CoreSearchQuery"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message spawner.core_components.search.v1.CoreSearchQuery.
 * Use `create(CoreSearchQuerySchema)` to create a new message.
 */
export const CoreSearchQuerySchema: GenMessage<CoreSearchQuery> = /*@__PURE__*/
  messageDesc(file_spawner_core_components_search_v1_search, 2);

/**
 * @generated from message spawner.core_components.search.v1.CoreSearchMatch
 */
export type CoreSearchMatch = Message<"spawner.core_components.search.v1.CoreSearchMatch"> & {
  /**
   * @generated from field: spawner.core_components.search.v1.CoreSearchResultType type = 1;
   */
  type: CoreSearchResultType;

  /**
   * @generated from field: string text = 2;
   */
  text: string;
};

/**
 * Describes the message spawner.core_components.search.v1.CoreSearchMatch.
 * Use `create(CoreSearchMatchSchema)` to create a new message.
 */
export const CoreSearchMatchSchema: GenMessage<CoreSearchMatch> = /*@__PURE__*/
  messageDesc(file_spawner_core_components_search_v1_search, 3);

/**
 * @generated from message spawner.core_components.search.v1.CoreSearchResult
 */
export type CoreSearchResult = Message<"spawner.core_components.search.v1.CoreSearchResult"> & {
  /**
   * @generated from field: repeated spawner.core_components.search.v1.CoreSearchMatch matches = 1;
   */
  matches: CoreSearchMatch[];
};

/**
 * Describes the message spawner.core_components.search.v1.CoreSearchResult.
 * Use `create(CoreSearchResultSchema)` to create a new message.
 */
export const CoreSearchResultSchema: GenMessage<CoreSearchResult> = /*@__PURE__*/
  messageDesc(file_spawner_core_components_search_v1_search, 4);

/**
 * @generated from message spawner.core_components.search.v1.CoreSearch
 */
export type CoreSearch = Message<"spawner.core_components.search.v1.CoreSearch"> & {
  /**
   * Only input.
   *
   * @generated from field: spawner.core_components.search.v1.CoreSearchConfiguration configuration = 1;
   */
  configuration?: CoreSearchConfiguration;

  /**
   * Only input. List of queries to search for.
   *
   * @generated from field: repeated spawner.core_components.search.v1.CoreSearchQuery queries = 2;
   */
  queries: CoreSearchQuery[];

  /**
   * Only output. The list of results, for each query.
   *
   * @generated from field: repeated spawner.core_components.search.v1.CoreSearchResult results = 3;
   */
  results: CoreSearchResult[];
};

/**
 * Describes the message spawner.core_components.search.v1.CoreSearch.
 * Use `create(CoreSearchSchema)` to create a new message.
 */
export const CoreSearchSchema: GenMessage<CoreSearch> = /*@__PURE__*/
  messageDesc(file_spawner_core_components_search_v1_search, 5);

/**
 * @generated from enum spawner.core_components.search.v1.CoreSearchResultType
 */
export enum CoreSearchResultType {
  /**
   * @generated from enum value: CORE_SEARCH_RESULT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CORE_SEARCH_RESULT_TYPE_KNOWLEDGE = 1;
   */
  KNOWLEDGE = 1,

  /**
   * @generated from enum value: CORE_SEARCH_RESULT_TYPE_OBSERVATION = 2;
   */
  OBSERVATION = 2,
}

/**
 * Describes the enum spawner.core_components.search.v1.CoreSearchResultType.
 */
export const CoreSearchResultTypeSchema: GenEnum<CoreSearchResultType> = /*@__PURE__*/
  enumDesc(file_spawner_core_components_search_v1_search, 0);

