// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/actor/v1/actor.proto (package spawner.actor.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/actor/v1/actor.proto.
 */
export const file_spawner_actor_v1_actor: GenFile = /*@__PURE__*/
  fileDesc("ChxzcGF3bmVyL2FjdG9yL3YxL2FjdG9yLnByb3RvEhBzcGF3bmVyLmFjdG9yLnYxImcKC1BsYXllckFjdG9yEgoKAmlkGAEgASgJEhQKDGRpc3BsYXlfbmFtZRgCIAEoCRIRCglhZ2VfZ3JvdXAYAyABKAkSDgoGZ2VuZGVyGAQgASgJEhMKC2Rlc2NyaXB0aW9uGAUgASgJIhgKCkFnZW50QWN0b3ISCgoCaWQYASABKAkiZQoFQWN0b3ISLgoHcGxheWVycxgBIAMoCzIdLnNwYXduZXIuYWN0b3IudjEuUGxheWVyQWN0b3ISLAoGYWdlbnRzGAMgAygLMhwuc3Bhd25lci5hY3Rvci52MS5BZ2VudEFjdG9yQoQBChRjb20uc3Bhd25lci5hY3Rvci52MUIKQWN0b3JQcm90b1ABogIDU0FYqgIQU3Bhd25lci5BY3Rvci5WMcoCEFNwYXduZXJcQWN0b3JcVjHiAhxTcGF3bmVyXEFjdG9yXFYxXEdQQk1ldGFkYXRh6gISU3Bhd25lcjo6QWN0b3I6OlYxYgZwcm90bzM");

/**
 * Encapsulates properties of a player. Used to populate the
 * user's profile for text generation, long-term memory management, etc.
 *
 * @generated from message spawner.actor.v1.PlayerActor
 */
export type PlayerActor = Message<"spawner.actor.v1.PlayerActor"> & {
  /**
   * Required field. Value should be unique for each player.
   * Spawner API does not verify consistency or uniqueness of the value.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Name of the player.
   *
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * Age group of player.
   * Refer to latest documentation for expected values.
   *
   * @generated from field: string age_group = 3;
   */
  ageGroup: string;

  /**
   * Gender of player.
   * Refer to latest documentation for expected values.
   *
   * @generated from field: string gender = 4;
   */
  gender: string;

  /**
   * The text description of the player.
   *
   * @generated from field: string description = 5;
   */
  description: string;
};

/**
 * Describes the message spawner.actor.v1.PlayerActor.
 * Use `create(PlayerActorSchema)` to create a new message.
 */
export const PlayerActorSchema: GenMessage<PlayerActor> = /*@__PURE__*/
  messageDesc(file_spawner_actor_v1_actor, 0);

/**
 * @generated from message spawner.actor.v1.AgentActor
 */
export type AgentActor = Message<"spawner.actor.v1.AgentActor"> & {
  /**
   * Required field. Value is generated on the server. Create 'world' to
   * generate a new agent id.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message spawner.actor.v1.AgentActor.
 * Use `create(AgentActorSchema)` to create a new message.
 */
export const AgentActorSchema: GenMessage<AgentActor> = /*@__PURE__*/
  messageDesc(file_spawner_actor_v1_actor, 1);

/**
 * Defines the actors within a channel.
 *
 * @generated from message spawner.actor.v1.Actor
 */
export type Actor = Message<"spawner.actor.v1.Actor"> & {
  /**
   * @generated from field: repeated spawner.actor.v1.PlayerActor players = 1;
   */
  players: PlayerActor[];

  /**
   * removed: 2
   *
   * @generated from field: repeated spawner.actor.v1.AgentActor agents = 3;
   */
  agents: AgentActor[];
};

/**
 * Describes the message spawner.actor.v1.Actor.
 * Use `create(ActorSchema)` to create a new message.
 */
export const ActorSchema: GenMessage<Actor> = /*@__PURE__*/
  messageDesc(file_spawner_actor_v1_actor, 2);

