// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/actor/v1/actor.proto (package spawner.actor.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/actor/v1/actor.proto.
 */
export const file_spawner_actor_v1_actor: GenFile = /*@__PURE__*/
  fileDesc("ChxzcGF3bmVyL2FjdG9yL3YxL2FjdG9yLnByb3RvEhBzcGF3bmVyLmFjdG9yLnYxImcKC1BsYXllckFjdG9yEgoKAmlkGAEgASgJEhQKDGRpc3BsYXlfbmFtZRgCIAEoCRIRCglhZ2VfZ3JvdXAYAyABKAkSDgoGZ2VuZGVyGAQgASgJEhMKC2Rlc2NyaXB0aW9uGAUgASgJIlkKDkNoYXJhY3RlckFjdG9yEgwKBG5hbWUYASABKAkSFAoMZGlzcGxheV9uYW1lGAIgASgJEhEKCWN1c3RvbV9pZBgDIAEoCRIQCghhZ2VudF9pZBgEIAEoCSIYCgpBZ2VudEFjdG9yEgoKAmlkGAEgASgJIp8BCgVBY3RvchIuCgdwbGF5ZXJzGAEgAygLMh0uc3Bhd25lci5hY3Rvci52MS5QbGF5ZXJBY3RvchI4CgpjaGFyYWN0ZXJzGAIgAygLMiAuc3Bhd25lci5hY3Rvci52MS5DaGFyYWN0ZXJBY3RvckICGAESLAoGYWdlbnRzGAMgAygLMhwuc3Bhd25lci5hY3Rvci52MS5BZ2VudEFjdG9yIkcKFkNoYXJhY3Rlck11dGF0aW9uRXZlbnQSFQoJY3VzdG9tX2lkGAEgASgJQgIYARIWCgpuYXJyYXRpdmVzGAIgAygJQgIYAUKEAQoUY29tLnNwYXduZXIuYWN0b3IudjFCCkFjdG9yUHJvdG9QAaICA1NBWKoCEFNwYXduZXIuQWN0b3IuVjHKAhBTcGF3bmVyXEFjdG9yXFYx4gIcU3Bhd25lclxBY3RvclxWMVxHUEJNZXRhZGF0YeoCElNwYXduZXI6OkFjdG9yOjpWMWIGcHJvdG8z");

/**
 * Encapsulates properties of a player. Used to populate the
 * user's profile for text generation, long-term memory management, etc.
 *
 * @generated from message spawner.actor.v1.PlayerActor
 */
export type PlayerActor = Message<"spawner.actor.v1.PlayerActor"> & {
  /**
   * Required field. Value should be unique for each player.
   * Spawner API does not verify consistency or uniqueness of the value.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Name of the player.
   *
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * Age group of player.
   * Refer to latest documentation for expected values.
   *
   * @generated from field: string age_group = 3;
   */
  ageGroup: string;

  /**
   * Gender of player.
   * Refer to latest documentation for expected values.
   *
   * @generated from field: string gender = 4;
   */
  gender: string;

  /**
   * The text description of the player.
   *
   * @generated from field: string description = 5;
   */
  description: string;
};

/**
 * Describes the message spawner.actor.v1.PlayerActor.
 * Use `create(PlayerActorSchema)` to create a new message.
 */
export const PlayerActorSchema: GenMessage<PlayerActor> = /*@__PURE__*/
  messageDesc(file_spawner_actor_v1_actor, 0);

/**
 * Deprecated. Encapsulates the identifiers of a character.
 *
 * @generated from message spawner.actor.v1.CharacterActor
 */
export type CharacterActor = Message<"spawner.actor.v1.CharacterActor"> & {
  /**
   * Only output. Relative resource path.
   * Format: `workspaces:{workspace_id}:characters:{character_id}`
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Name of the character.
   *
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * Indicates the custom identifier of the character. Note that it
   * may differ from the character id used for storage.
   *
   * @generated from field: string custom_id = 3;
   */
  customId: string;

  /**
   * Indicates the agent id of the character. Value should exist if the
   * character is being used as an agent. If the character is used without agent
   * running, this may be left empty.
   *
   * @generated from field: string agent_id = 4;
   */
  agentId: string;
};

/**
 * Describes the message spawner.actor.v1.CharacterActor.
 * Use `create(CharacterActorSchema)` to create a new message.
 */
export const CharacterActorSchema: GenMessage<CharacterActor> = /*@__PURE__*/
  messageDesc(file_spawner_actor_v1_actor, 1);

/**
 * @generated from message spawner.actor.v1.AgentActor
 */
export type AgentActor = Message<"spawner.actor.v1.AgentActor"> & {
  /**
   * Required field. Value is generated on the server. Create 'world' to
   * generate a new agent id.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message spawner.actor.v1.AgentActor.
 * Use `create(AgentActorSchema)` to create a new message.
 */
export const AgentActorSchema: GenMessage<AgentActor> = /*@__PURE__*/
  messageDesc(file_spawner_actor_v1_actor, 2);

/**
 * Defines the actors within a channel.
 *
 * @generated from message spawner.actor.v1.Actor
 */
export type Actor = Message<"spawner.actor.v1.Actor"> & {
  /**
   * @generated from field: repeated spawner.actor.v1.PlayerActor players = 1;
   */
  players: PlayerActor[];

  /**
   * @generated from field: repeated spawner.actor.v1.CharacterActor characters = 2 [deprecated = true];
   * @deprecated
   */
  characters: CharacterActor[];

  /**
   * @generated from field: repeated spawner.actor.v1.AgentActor agents = 3;
   */
  agents: AgentActor[];
};

/**
 * Describes the message spawner.actor.v1.Actor.
 * Use `create(ActorSchema)` to create a new message.
 */
export const ActorSchema: GenMessage<Actor> = /*@__PURE__*/
  messageDesc(file_spawner_actor_v1_actor, 3);

/**
 * Deprecated.
 *
 * @generated from message spawner.actor.v1.CharacterMutationEvent
 */
export type CharacterMutationEvent = Message<"spawner.actor.v1.CharacterMutationEvent"> & {
  /**
   * Indicates the custom identifier of the character. Note that it
   * may differ from the character id used for storage.
   *
   * @generated from field: string custom_id = 1 [deprecated = true];
   * @deprecated
   */
  customId: string;

  /**
   * List of strings depicting the inner monologue/narrative of the character.
   * Client is able to modify this at runtime.
   *
   * @generated from field: repeated string narratives = 2 [deprecated = true];
   * @deprecated
   */
  narratives: string[];
};

/**
 * Describes the message spawner.actor.v1.CharacterMutationEvent.
 * Use `create(CharacterMutationEventSchema)` to create a new message.
 */
export const CharacterMutationEventSchema: GenMessage<CharacterMutationEvent> = /*@__PURE__*/
  messageDesc(file_spawner_actor_v1_actor, 4);

