// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/packet_components/input_filter/v1/input_filter.proto (package spawner.packet_components.input_filter.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/packet_components/input_filter/v1/input_filter.proto.
 */
export const file_spawner_packet_components_input_filter_v1_input_filter: GenFile = /*@__PURE__*/
  fileDesc("CjxzcGF3bmVyL3BhY2tldF9jb21wb25lbnRzL2lucHV0X2ZpbHRlci92MS9pbnB1dF9maWx0ZXIucHJvdG8SKXNwYXduZXIucGFja2V0X2NvbXBvbmVudHMuaW5wdXRfZmlsdGVyLnYxIi8KEElucHV0RmlsdGVyTWF0Y2gSDQoFbGFiZWwYASABKAkSDAoEdGV4dBgCIAEoCSKYAQoQSW5wdXRGaWx0ZXJFdmVudBIUCgx1dHRlcmFuY2VfaWQYASABKAkSEgoKaXNfZmxhZ2dlZBgDIAEoCBIMCgR0ZXh0GAQgASgJEkwKB21hdGNoZXMYBSADKAsyOy5zcGF3bmVyLnBhY2tldF9jb21wb25lbnRzLmlucHV0X2ZpbHRlci52MS5JbnB1dEZpbHRlck1hdGNoQoACCi1jb20uc3Bhd25lci5wYWNrZXRfY29tcG9uZW50cy5pbnB1dF9maWx0ZXIudjFCEElucHV0RmlsdGVyUHJvdG9QAaICA1NQSaoCJ1NwYXduZXIuUGFja2V0Q29tcG9uZW50cy5JbnB1dEZpbHRlci5WMcoCJ1NwYXduZXJcUGFja2V0Q29tcG9uZW50c1xJbnB1dEZpbHRlclxWMeICM1NwYXduZXJcUGFja2V0Q29tcG9uZW50c1xJbnB1dEZpbHRlclxWMVxHUEJNZXRhZGF0YeoCKlNwYXduZXI6OlBhY2tldENvbXBvbmVudHM6OklucHV0RmlsdGVyOjpWMWIGcHJvdG8z");

/**
 * @generated from message spawner.packet_components.input_filter.v1.InputFilterMatch
 */
export type InputFilterMatch = Message<"spawner.packet_components.input_filter.v1.InputFilterMatch"> & {
  /**
   * @generated from field: string label = 1;
   */
  label: string;

  /**
   * @generated from field: string text = 2;
   */
  text: string;
};

/**
 * Describes the message spawner.packet_components.input_filter.v1.InputFilterMatch.
 * Use `create(InputFilterMatchSchema)` to create a new message.
 */
export const InputFilterMatchSchema: GenMessage<InputFilterMatch> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_input_filter_v1_input_filter, 0);

/**
 * Represents a filter result, which may be triggered
 * when the player input is flagged for moderation
 * or filtered words set in the workspace.
 *
 * @generated from message spawner.packet_components.input_filter.v1.InputFilterEvent
 */
export type InputFilterEvent = Message<"spawner.packet_components.input_filter.v1.InputFilterEvent"> & {
  /**
   * Identifies a grouping of multiple packages.
   *
   * @generated from field: string utterance_id = 1;
   */
  utteranceId: string;

  /**
   * `True` if the input has been filtered.
   *
   * @generated from field: bool is_flagged = 3;
   */
  isFlagged: boolean;

  /**
   * Response returned by the target character. This may be empty depending on
   * character settings. Client must handle for each case.
   *
   * @generated from field: string text = 4;
   */
  text: string;

  /**
   * Indicates what was filtered based on workspace settings. Assume empty if
   * the input was moderated.
   *
   * @generated from field: repeated spawner.packet_components.input_filter.v1.InputFilterMatch matches = 5;
   */
  matches: InputFilterMatch[];
};

/**
 * Describes the message spawner.packet_components.input_filter.v1.InputFilterEvent.
 * Use `create(InputFilterEventSchema)` to create a new message.
 */
export const InputFilterEventSchema: GenMessage<InputFilterEvent> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_input_filter_v1_input_filter, 1);

