// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/packet_components/agent/v1/agent.proto (package spawner.packet_components.agent.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { ObjectiveEvent } from "../../objective/v1/objective_pb";
import { file_spawner_packet_components_objective_v1_objective } from "../../objective/v1/objective_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/packet_components/agent/v1/agent.proto.
 */
export const file_spawner_packet_components_agent_v1_agent: GenFile = /*@__PURE__*/
  fileDesc("Ci5zcGF3bmVyL3BhY2tldF9jb21wb25lbnRzL2FnZW50L3YxL2FnZW50LnByb3RvEiJzcGF3bmVyLnBhY2tldF9jb21wb25lbnRzLmFnZW50LnYxIsEBCg9BZ2VudENvbnRyb2xsZXISQAoEdHlwZRgBIAEoDjIyLnNwYXduZXIucGFja2V0X2NvbXBvbmVudHMuYWdlbnQudjEuQWdlbnRFdmVudFR5cGUSFAoIYWdlbnRfaWQYAiABKAlCAhgBEksKCW9iamVjdGl2ZRgDIAEoCzI2LnNwYXduZXIucGFja2V0X2NvbXBvbmVudHMub2JqZWN0aXZlLnYxLk9iamVjdGl2ZUV2ZW50SABCCQoHcGF5bG9hZCpSCg5BZ2VudEV2ZW50VHlwZRIgChxBR0VOVF9FVkVOVF9UWVBFX1VOU1BFQ0lGSUVEEAASHgoaQUdFTlRfRVZFTlRfVFlQRV9PQkpFQ1RJVkUQAULbAQomY29tLnNwYXduZXIucGFja2V0X2NvbXBvbmVudHMuYWdlbnQudjFCCkFnZW50UHJvdG9QAaICA1NQQaoCIVNwYXduZXIuUGFja2V0Q29tcG9uZW50cy5BZ2VudC5WMcoCIVNwYXduZXJcUGFja2V0Q29tcG9uZW50c1xBZ2VudFxWMeICLVNwYXduZXJcUGFja2V0Q29tcG9uZW50c1xBZ2VudFxWMVxHUEJNZXRhZGF0YeoCJFNwYXduZXI6OlBhY2tldENvbXBvbmVudHM6OkFnZW50OjpWMWIGcHJvdG8z", [file_spawner_packet_components_objective_v1_objective]);

/**
 * @generated from message spawner.packet_components.agent.v1.AgentController
 */
export type AgentController = Message<"spawner.packet_components.agent.v1.AgentController"> & {
  /**
   * @generated from field: spawner.packet_components.agent.v1.AgentEventType type = 1;
   */
  type: AgentEventType;

  /**
   * @generated from field: string agent_id = 2 [deprecated = true];
   * @deprecated
   */
  agentId: string;

  /**
   * @generated from oneof spawner.packet_components.agent.v1.AgentController.payload
   */
  payload: {
    /**
     * @generated from field: spawner.packet_components.objective.v1.ObjectiveEvent objective = 3;
     */
    value: ObjectiveEvent;
    case: "objective";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message spawner.packet_components.agent.v1.AgentController.
 * Use `create(AgentControllerSchema)` to create a new message.
 */
export const AgentControllerSchema: GenMessage<AgentController> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_agent_v1_agent, 0);

/**
 * @generated from enum spawner.packet_components.agent.v1.AgentEventType
 */
export enum AgentEventType {
  /**
   * @generated from enum value: AGENT_EVENT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * An objective defines what the agent is pursuing. An objective is necessary
   * for the agent to decide on actions.
   *
   * @generated from enum value: AGENT_EVENT_TYPE_OBJECTIVE = 1;
   */
  OBJECTIVE = 1,
}

/**
 * Describes the enum spawner.packet_components.agent.v1.AgentEventType.
 */
export const AgentEventTypeSchema: GenEnum<AgentEventType> = /*@__PURE__*/
  enumDesc(file_spawner_packet_components_agent_v1_agent, 0);

