// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/language_code/v1/language_code.proto (package spawner.language_code.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file spawner/language_code/v1/language_code.proto.
 */
export const file_spawner_language_code_v1_language_code: GenFile = /*@__PURE__*/
  fileDesc("CixzcGF3bmVyL2xhbmd1YWdlX2NvZGUvdjEvbGFuZ3VhZ2VfY29kZS5wcm90bxIYc3Bhd25lci5sYW5ndWFnZV9jb2RlLnYxKlkKDExhbmd1YWdlQ29kZRIdChlMQU5HVUFHRV9DT0RFX1VOU1BFQ0lGSUVEEAASFAoQTEFOR1VBR0VfQ09ERV9FThABEhQKEExBTkdVQUdFX0NPREVfSkEQAkKvAQocY29tLnNwYXduZXIubGFuZ3VhZ2VfY29kZS52MUIRTGFuZ3VhZ2VDb2RlUHJvdG9QAaICA1NMWKoCF1NwYXduZXIuTGFuZ3VhZ2VDb2RlLlYxygIXU3Bhd25lclxMYW5ndWFnZUNvZGVcVjHiAiNTcGF3bmVyXExhbmd1YWdlQ29kZVxWMVxHUEJNZXRhZGF0YeoCGVNwYXduZXI6Okxhbmd1YWdlQ29kZTo6VjFiBnByb3RvMw");

/**
 * @generated from enum spawner.language_code.v1.LanguageCode
 */
export enum LanguageCode {
  /**
   * @generated from enum value: LANGUAGE_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: LANGUAGE_CODE_EN = 1;
   */
  EN = 1,

  /**
   * @generated from enum value: LANGUAGE_CODE_JA = 2;
   */
  JA = 2,
}

/**
 * Describes the enum spawner.language_code.v1.LanguageCode.
 */
export const LanguageCodeSchema: GenEnum<LanguageCode> = /*@__PURE__*/
  enumDesc(file_spawner_language_code_v1_language_code, 0);

