// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/prompt_injection/v1/prompt_injection.proto (package spawner.prompt_injection.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/prompt_injection/v1/prompt_injection.proto.
 */
export const file_spawner_prompt_injection_v1_prompt_injection: GenFile = /*@__PURE__*/
  fileDesc("CjJzcGF3bmVyL3Byb21wdF9pbmplY3Rpb24vdjEvcHJvbXB0X2luamVjdGlvbi5wcm90bxIbc3Bhd25lci5wcm9tcHRfaW5qZWN0aW9uLnYxIlIKHVByb21wdEluamVjdGlvbkRldGVjdG9yUmVzdWx0EhEKCWphaWxicmVhaxgBIAEoAhIQCghyb2xlcGxheRgCIAEoAhIMCgRjb2RlGAMgASgCIowBChRQcm9tcHRJbmplY3Rpb25FdmVudBIUCgx1dHRlcmFuY2VfaWQYASABKAkSEgoKaXNfZmxhZ2dlZBgCIAEoCBJKCgZyZXN1bHQYAyABKAsyOi5zcGF3bmVyLnByb21wdF9pbmplY3Rpb24udjEuUHJvbXB0SW5qZWN0aW9uRGV0ZWN0b3JSZXN1bHRCwQEKH2NvbS5zcGF3bmVyLnByb21wdF9pbmplY3Rpb24udjFCFFByb21wdEluamVjdGlvblByb3RvUAGiAgNTUFiqAhpTcGF3bmVyLlByb21wdEluamVjdGlvbi5WMcoCGlNwYXduZXJcUHJvbXB0SW5qZWN0aW9uXFYx4gImU3Bhd25lclxQcm9tcHRJbmplY3Rpb25cVjFcR1BCTWV0YWRhdGHqAhxTcGF3bmVyOjpQcm9tcHRJbmplY3Rpb246OlYxYgZwcm90bzM");

/**
 * @generated from message spawner.prompt_injection.v1.PromptInjectionDetectorResult
 */
export type PromptInjectionDetectorResult = Message<"spawner.prompt_injection.v1.PromptInjectionDetectorResult"> & {
  /**
   * @generated from field: float jailbreak = 1;
   */
  jailbreak: number;

  /**
   * @generated from field: float roleplay = 2;
   */
  roleplay: number;

  /**
   * @generated from field: float code = 3;
   */
  code: number;
};

/**
 * Describes the message spawner.prompt_injection.v1.PromptInjectionDetectorResult.
 * Use `create(PromptInjectionDetectorResultSchema)` to create a new message.
 */
export const PromptInjectionDetectorResultSchema: GenMessage<PromptInjectionDetectorResult> = /*@__PURE__*/
  messageDesc(file_spawner_prompt_injection_v1_prompt_injection, 0);

/**
 * Represents a prompt injection detection result.
 *
 * @generated from message spawner.prompt_injection.v1.PromptInjectionEvent
 */
export type PromptInjectionEvent = Message<"spawner.prompt_injection.v1.PromptInjectionEvent"> & {
  /**
   * Identifies a grouping of multiple packages.
   *
   * @generated from field: string utterance_id = 1;
   */
  utteranceId: string;

  /**
   * `True` if prompt injection has been detected.
   *
   * @generated from field: bool is_flagged = 2;
   */
  isFlagged: boolean;

  /**
   * @generated from field: spawner.prompt_injection.v1.PromptInjectionDetectorResult result = 3;
   */
  result?: PromptInjectionDetectorResult;
};

/**
 * Describes the message spawner.prompt_injection.v1.PromptInjectionEvent.
 * Use `create(PromptInjectionEventSchema)` to create a new message.
 */
export const PromptInjectionEventSchema: GenMessage<PromptInjectionEvent> = /*@__PURE__*/
  messageDesc(file_spawner_prompt_injection_v1_prompt_injection, 1);

