// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/packet_components/emotion/v1/emotion.proto (package spawner.packet_components.emotion.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/packet_components/emotion/v1/emotion.proto.
 */
export const file_spawner_packet_components_emotion_v1_emotion: GenFile = /*@__PURE__*/
  fileDesc("CjJzcGF3bmVyL3BhY2tldF9jb21wb25lbnRzL2Vtb3Rpb24vdjEvZW1vdGlvbi5wcm90bxIkc3Bhd25lci5wYWNrZXRfY29tcG9uZW50cy5lbW90aW9uLnYxImwKDEVtb3Rpb25TY29yZRILCgNqb3kYASABKAISDwoHc2FkbmVzcxgCIAEoAhINCgVhbmdlchgDIAEoAhIMCgRmZWFyGAQgASgCEg8KB2Rpc2d1c3QYBSABKAISEAoIc3VycHJpc2UYBiABKAIirAEKDEVtb3Rpb25FdmVudBIUCgx1dHRlcmFuY2VfaWQYASABKAkSQwoGcmVzdWx0GAIgASgOMjMuc3Bhd25lci5wYWNrZXRfY29tcG9uZW50cy5lbW90aW9uLnYxLkVtb3Rpb25SZXN1bHQSQQoFc2NvcmUYAyABKAsyMi5zcGF3bmVyLnBhY2tldF9jb21wb25lbnRzLmVtb3Rpb24udjEuRW1vdGlvblNjb3JlKusBCg1FbW90aW9uUmVzdWx0Eh4KGkVNT1RJT05fUkVTVUxUX1VOU1BFQ0lGSUVEEAASGgoWRU1PVElPTl9SRVNVTFRfTkVVVFJBTBABEhYKEkVNT1RJT05fUkVTVUxUX0pPWRACEhoKFkVNT1RJT05fUkVTVUxUX1NBRE5FU1MQAxIYChRFTU9USU9OX1JFU1VMVF9BTkdFUhAEEhcKE0VNT1RJT05fUkVTVUxUX0ZFQVIQBRIaChZFTU9USU9OX1JFU1VMVF9ESVNHVVNUEAYSGwoXRU1PVElPTl9SRVNVTFRfU1VSUFJJU0UQB0LnAQooY29tLnNwYXduZXIucGFja2V0X2NvbXBvbmVudHMuZW1vdGlvbi52MUIMRW1vdGlvblByb3RvUAGiAgNTUEWqAiNTcGF3bmVyLlBhY2tldENvbXBvbmVudHMuRW1vdGlvbi5WMcoCI1NwYXduZXJcUGFja2V0Q29tcG9uZW50c1xFbW90aW9uXFYx4gIvU3Bhd25lclxQYWNrZXRDb21wb25lbnRzXEVtb3Rpb25cVjFcR1BCTWV0YWRhdGHqAiZTcGF3bmVyOjpQYWNrZXRDb21wb25lbnRzOjpFbW90aW9uOjpWMWIGcHJvdG8z");

/**
 * @generated from message spawner.packet_components.emotion.v1.EmotionScore
 */
export type EmotionScore = Message<"spawner.packet_components.emotion.v1.EmotionScore"> & {
  /**
   * @generated from field: float joy = 1;
   */
  joy: number;

  /**
   * @generated from field: float sadness = 2;
   */
  sadness: number;

  /**
   * @generated from field: float anger = 3;
   */
  anger: number;

  /**
   * @generated from field: float fear = 4;
   */
  fear: number;

  /**
   * @generated from field: float disgust = 5;
   */
  disgust: number;

  /**
   * @generated from field: float surprise = 6;
   */
  surprise: number;
};

/**
 * Describes the message spawner.packet_components.emotion.v1.EmotionScore.
 * Use `create(EmotionScoreSchema)` to create a new message.
 */
export const EmotionScoreSchema: GenMessage<EmotionScore> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_emotion_v1_emotion, 0);

/**
 * Output only. Indicates the emotion detection results.
 *
 * @generated from message spawner.packet_components.emotion.v1.EmotionEvent
 */
export type EmotionEvent = Message<"spawner.packet_components.emotion.v1.EmotionEvent"> & {
  /**
   * Identifies a grouping of multiple packages.
   *
   * @generated from field: string utterance_id = 1;
   */
  utteranceId: string;

  /**
   * Emotion detected for the most recent invocation.
   *
   * @generated from field: spawner.packet_components.emotion.v1.EmotionResult result = 2;
   */
  result: EmotionResult;

  /**
   * Emotion scores calculated based on past scores and sensitivity settings.
   *
   * @generated from field: spawner.packet_components.emotion.v1.EmotionScore score = 3;
   */
  score?: EmotionScore;
};

/**
 * Describes the message spawner.packet_components.emotion.v1.EmotionEvent.
 * Use `create(EmotionEventSchema)` to create a new message.
 */
export const EmotionEventSchema: GenMessage<EmotionEvent> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_emotion_v1_emotion, 1);

/**
 * @generated from enum spawner.packet_components.emotion.v1.EmotionResult
 */
export enum EmotionResult {
  /**
   * @generated from enum value: EMOTION_RESULT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: EMOTION_RESULT_NEUTRAL = 1;
   */
  NEUTRAL = 1,

  /**
   * @generated from enum value: EMOTION_RESULT_JOY = 2;
   */
  JOY = 2,

  /**
   * @generated from enum value: EMOTION_RESULT_SADNESS = 3;
   */
  SADNESS = 3,

  /**
   * @generated from enum value: EMOTION_RESULT_ANGER = 4;
   */
  ANGER = 4,

  /**
   * @generated from enum value: EMOTION_RESULT_FEAR = 5;
   */
  FEAR = 5,

  /**
   * @generated from enum value: EMOTION_RESULT_DISGUST = 6;
   */
  DISGUST = 6,

  /**
   * @generated from enum value: EMOTION_RESULT_SURPRISE = 7;
   */
  SURPRISE = 7,
}

/**
 * Describes the enum spawner.packet_components.emotion.v1.EmotionResult.
 */
export const EmotionResultSchema: GenEnum<EmotionResult> = /*@__PURE__*/
  enumDesc(file_spawner_packet_components_emotion_v1_emotion, 0);

