// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/packet_components/routing/v1/routing.proto (package spawner.packet_components.routing.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/packet_components/routing/v1/routing.proto.
 */
export const file_spawner_packet_components_routing_v1_routing: GenFile = /*@__PURE__*/
  fileDesc("CjJzcGF3bmVyL3BhY2tldF9jb21wb25lbnRzL3JvdXRpbmcvdjEvcm91dGluZy5wcm90bxIkc3Bhd25lci5wYWNrZXRfY29tcG9uZW50cy5yb3V0aW5nLnYxIi8KC0V2ZW50UGxheWVyEgoKAmlkGAEgASgJEhQKDGRpc3BsYXlfbmFtZRgCIAEoCSIYCgpFdmVudEFnZW50EgoKAmlkGAEgASgJIuMBCgpFdmVudEFjdG9yEkIKBHR5cGUYASABKA4yNC5zcGF3bmVyLnBhY2tldF9jb21wb25lbnRzLnJvdXRpbmcudjEuRXZlbnRBY3RvclR5cGUSQwoGcGxheWVyGAIgASgLMjEuc3Bhd25lci5wYWNrZXRfY29tcG9uZW50cy5yb3V0aW5nLnYxLkV2ZW50UGxheWVySAASQQoFYWdlbnQYBCABKAsyMC5zcGF3bmVyLnBhY2tldF9jb21wb25lbnRzLnJvdXRpbmcudjEuRXZlbnRBZ2VudEgAQgkKB3BheWxvYWQijQEKB1JvdXRpbmcSQAoGc291cmNlGAEgASgLMjAuc3Bhd25lci5wYWNrZXRfY29tcG9uZW50cy5yb3V0aW5nLnYxLkV2ZW50QWN0b3ISQAoGdGFyZ2V0GAIgASgLMjAuc3Bhd25lci5wYWNrZXRfY29tcG9uZW50cy5yb3V0aW5nLnYxLkV2ZW50QWN0b3IqhgEKDkV2ZW50QWN0b3JUeXBlEiAKHEVWRU5UX0FDVE9SX1RZUEVfVU5TUEVDSUZJRUQQABIbChdFVkVOVF9BQ1RPUl9UWVBFX1BMQVlFUhABEhoKFkVWRU5UX0FDVE9SX1RZUEVfQUdFTlQQAxIZChVFVkVOVF9BQ1RPUl9UWVBFX0hFUkUQBELnAQooY29tLnNwYXduZXIucGFja2V0X2NvbXBvbmVudHMucm91dGluZy52MUIMUm91dGluZ1Byb3RvUAGiAgNTUFKqAiNTcGF3bmVyLlBhY2tldENvbXBvbmVudHMuUm91dGluZy5WMcoCI1NwYXduZXJcUGFja2V0Q29tcG9uZW50c1xSb3V0aW5nXFYx4gIvU3Bhd25lclxQYWNrZXRDb21wb25lbnRzXFJvdXRpbmdcVjFcR1BCTWV0YWRhdGHqAiZTcGF3bmVyOjpQYWNrZXRDb21wb25lbnRzOjpSb3V0aW5nOjpWMWIGcHJvdG8z");

/**
 * @generated from message spawner.packet_components.routing.v1.EventPlayer
 */
export type EventPlayer = Message<"spawner.packet_components.routing.v1.EventPlayer"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Output only.
   *
   * @generated from field: string display_name = 2;
   */
  displayName: string;
};

/**
 * Describes the message spawner.packet_components.routing.v1.EventPlayer.
 * Use `create(EventPlayerSchema)` to create a new message.
 */
export const EventPlayerSchema: GenMessage<EventPlayer> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_routing_v1_routing, 0);

/**
 * @generated from message spawner.packet_components.routing.v1.EventAgent
 */
export type EventAgent = Message<"spawner.packet_components.routing.v1.EventAgent"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message spawner.packet_components.routing.v1.EventAgent.
 * Use `create(EventAgentSchema)` to create a new message.
 */
export const EventAgentSchema: GenMessage<EventAgent> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_routing_v1_routing, 1);

/**
 * @generated from message spawner.packet_components.routing.v1.EventActor
 */
export type EventActor = Message<"spawner.packet_components.routing.v1.EventActor"> & {
  /**
   * @generated from field: spawner.packet_components.routing.v1.EventActorType type = 1;
   */
  type: EventActorType;

  /**
   * @generated from oneof spawner.packet_components.routing.v1.EventActor.payload
   */
  payload: {
    /**
     * @generated from field: spawner.packet_components.routing.v1.EventPlayer player = 2;
     */
    value: EventPlayer;
    case: "player";
  } | {
    /**
     * @generated from field: spawner.packet_components.routing.v1.EventAgent agent = 4;
     */
    value: EventAgent;
    case: "agent";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message spawner.packet_components.routing.v1.EventActor.
 * Use `create(EventActorSchema)` to create a new message.
 */
export const EventActorSchema: GenMessage<EventActor> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_routing_v1_routing, 2);

/**
 * @generated from message spawner.packet_components.routing.v1.Routing
 */
export type Routing = Message<"spawner.packet_components.routing.v1.Routing"> & {
  /**
   * Source actor triggering the event. This is usually a player,
   * but may be an NPC for NPC-NPC events.
   *
   * @generated from field: spawner.packet_components.routing.v1.EventActor source = 1;
   */
  source?: EventActor;

  /**
   * Target actor that responds to the input. This is usually a character.
   *
   * @generated from field: spawner.packet_components.routing.v1.EventActor target = 2;
   */
  target?: EventActor;
};

/**
 * Describes the message spawner.packet_components.routing.v1.Routing.
 * Use `create(RoutingSchema)` to create a new message.
 */
export const RoutingSchema: GenMessage<Routing> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_routing_v1_routing, 3);

/**
 * @generated from enum spawner.packet_components.routing.v1.EventActorType
 */
export enum EventActorType {
  /**
   * @generated from enum value: EVENT_ACTOR_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: EVENT_ACTOR_TYPE_PLAYER = 1;
   */
  PLAYER = 1,

  /**
   * removed: 2
   *
   * @generated from enum value: EVENT_ACTOR_TYPE_AGENT = 3;
   */
  AGENT = 3,

  /**
   * Experimental. Only for event target field. Allows targeting
   * all actors in the interaction space.
   *
   * @generated from enum value: EVENT_ACTOR_TYPE_HERE = 4;
   */
  HERE = 4,
}

/**
 * Describes the enum spawner.packet_components.routing.v1.EventActorType.
 */
export const EventActorTypeSchema: GenEnum<EventActorType> = /*@__PURE__*/
  enumDesc(file_spawner_packet_components_routing_v1_routing, 0);

