// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/packet_components/text/v1/text.proto (package spawner.packet_components.text.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/packet_components/text/v1/text.proto.
 */
export const file_spawner_packet_components_text_v1_text: GenFile = /*@__PURE__*/
  fileDesc("CixzcGF3bmVyL3BhY2tldF9jb21wb25lbnRzL3RleHQvdjEvdGV4dC5wcm90bxIhc3Bhd25lci5wYWNrZXRfY29tcG9uZW50cy50ZXh0LnYxIkoKEENvbW1hbmRUcmlnZ2VyZWQSDAoEbmFtZRgBIAEoCRIVCgljdXN0b21faWQYAiABKAlCAhgBEhEKCWNsaWVudF9pZBgDIAEoCSKqAQoJVGV4dEV2ZW50EhQKDHV0dGVyYW5jZV9pZBgBIAEoCRIMCgR0ZXh0GAIgASgJEg0KBWRlbHRhGAMgASgJEg0KBWZpbmFsGAQgASgIEkQKB2NvbW1hbmQYBSABKAsyMy5zcGF3bmVyLnBhY2tldF9jb21wb25lbnRzLnRleHQudjEuQ29tbWFuZFRyaWdnZXJlZBIVCg1maWVsZF9vZl92aWV3GAcgASgMQtUBCiVjb20uc3Bhd25lci5wYWNrZXRfY29tcG9uZW50cy50ZXh0LnYxQglUZXh0UHJvdG9QAaICA1NQVKoCIFNwYXduZXIuUGFja2V0Q29tcG9uZW50cy5UZXh0LlYxygIgU3Bhd25lclxQYWNrZXRDb21wb25lbnRzXFRleHRcVjHiAixTcGF3bmVyXFBhY2tldENvbXBvbmVudHNcVGV4dFxWMVxHUEJNZXRhZGF0YeoCI1NwYXduZXI6OlBhY2tldENvbXBvbmVudHM6OlRleHQ6OlYxYgZwcm90bzM");

/**
 * @generated from message spawner.packet_components.text.v1.CommandTriggered
 */
export type CommandTriggered = Message<"spawner.packet_components.text.v1.CommandTriggered"> & {
  /**
   * Relative resource path.
   * Format: `workspaces:{workspace_id}:commands:{command_id}`
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Custom identifier set in the workspace.
   *
   * @generated from field: string custom_id = 2 [deprecated = true];
   * @deprecated
   */
  customId: string;

  /**
   * Custom identifier used in the client. This may be set in the console. This
   * replaced `custom_id`.
   *
   * @generated from field: string client_id = 3;
   */
  clientId: string;
};

/**
 * Describes the message spawner.packet_components.text.v1.CommandTriggered.
 * Use `create(CommandTriggeredSchema)` to create a new message.
 */
export const CommandTriggeredSchema: GenMessage<CommandTriggered> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_text_v1_text, 0);

/**
 * TextEvent represents text input and output. Assumes output streamed per token
 * using `delta` value.
 *
 * @generated from message spawner.packet_components.text.v1.TextEvent
 */
export type TextEvent = Message<"spawner.packet_components.text.v1.TextEvent"> & {
  /**
   * Required. Identifies a grouping of multiple packages. For example, a text
   * event may trigger emotion events, etc. The client should be able to
   * identify related packets.
   *
   * @generated from field: string utterance_id = 1;
   */
  utteranceId: string;

  /**
   * Represents text input or output. For output text, the content of this field
   * may not be the final result; for finalized text, use `final`.
   *
   * @generated from field: string text = 2;
   */
  text: string;

  /**
   * Only output. The most recent token generated. Value is expected to be used
   * to display streamed response in runtime.
   *
   * @generated from field: string delta = 3;
   */
  delta: string;

  /**
   * Only output. Indicates that the text generation has finalized. Note that
   * the value of `text` may change as long as this is False.
   *
   * @generated from field: bool final = 4;
   */
  final: boolean;

  /**
   * Only output. Indicates the command that was triggered. This is only
   * populated when a command has been triggered.
   *
   * @generated from field: spawner.packet_components.text.v1.CommandTriggered command = 5;
   */
  command?: CommandTriggered;

  /**
   * Only input. Accepts an image as binary data. The image indicates the field
   * of view of the agent. Use to ground agent response to its surroundings.
   *
   * @generated from field: bytes field_of_view = 7;
   */
  fieldOfView: Uint8Array;
};

/**
 * Describes the message spawner.packet_components.text.v1.TextEvent.
 * Use `create(TextEventSchema)` to create a new message.
 */
export const TextEventSchema: GenMessage<TextEvent> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_text_v1_text, 1);

