// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/input_filter/v1/input_filter.proto (package spawner.input_filter.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/input_filter/v1/input_filter.proto.
 */
export const file_spawner_input_filter_v1_input_filter: GenFile = /*@__PURE__*/
  fileDesc("CipzcGF3bmVyL2lucHV0X2ZpbHRlci92MS9pbnB1dF9maWx0ZXIucHJvdG8SF3NwYXduZXIuaW5wdXRfZmlsdGVyLnYxIi8KEElucHV0RmlsdGVyTWF0Y2gSDQoFbGFiZWwYASABKAkSDAoEdGV4dBgCIAEoCSK+AQoQSW5wdXRGaWx0ZXJFdmVudBIUCgx1dHRlcmFuY2VfaWQYASABKAkSNgoEdHlwZRgCIAEoDjIoLnNwYXduZXIuaW5wdXRfZmlsdGVyLnYxLklucHV0RmlsdGVyVHlwZRISCgppc19mbGFnZ2VkGAMgASgIEgwKBHRleHQYBCABKAkSOgoHbWF0Y2hlcxgFIAMoCzIpLnNwYXduZXIuaW5wdXRfZmlsdGVyLnYxLklucHV0RmlsdGVyTWF0Y2gqdAoPSW5wdXRGaWx0ZXJUeXBlEiEKHUlOUFVUX0ZJTFRFUl9UWVBFX1VOU1BFQ0lGSUVEEAASIAocSU5QVVRfRklMVEVSX1RZUEVfTU9ERVJBVElPThABEhwKGElOUFVUX0ZJTFRFUl9UWVBFX0NVU1RPTRACQqkBChtjb20uc3Bhd25lci5pbnB1dF9maWx0ZXIudjFCEElucHV0RmlsdGVyUHJvdG9QAaICA1NJWKoCFlNwYXduZXIuSW5wdXRGaWx0ZXIuVjHKAhZTcGF3bmVyXElucHV0RmlsdGVyXFYx4gIiU3Bhd25lclxJbnB1dEZpbHRlclxWMVxHUEJNZXRhZGF0YeoCGFNwYXduZXI6OklucHV0RmlsdGVyOjpWMWIGcHJvdG8z");

/**
 * @generated from message spawner.input_filter.v1.InputFilterMatch
 */
export type InputFilterMatch = Message<"spawner.input_filter.v1.InputFilterMatch"> & {
  /**
   * @generated from field: string label = 1;
   */
  label: string;

  /**
   * @generated from field: string text = 2;
   */
  text: string;
};

/**
 * Describes the message spawner.input_filter.v1.InputFilterMatch.
 * Use `create(InputFilterMatchSchema)` to create a new message.
 */
export const InputFilterMatchSchema: GenMessage<InputFilterMatch> = /*@__PURE__*/
  messageDesc(file_spawner_input_filter_v1_input_filter, 0);

/**
 * Represents a filter result, which may be triggered
 * when the player input is flagged for moderation
 * or filtered words set in the workspace.
 *
 * @generated from message spawner.input_filter.v1.InputFilterEvent
 */
export type InputFilterEvent = Message<"spawner.input_filter.v1.InputFilterEvent"> & {
  /**
   * Identifies a grouping of multiple packages.
   *
   * @generated from field: string utterance_id = 1;
   */
  utteranceId: string;

  /**
   * Indicates the reason the input has been flagged.
   *
   * @generated from field: spawner.input_filter.v1.InputFilterType type = 2;
   */
  type: InputFilterType;

  /**
   * `True` if the input has been filtered.
   *
   * @generated from field: bool is_flagged = 3;
   */
  isFlagged: boolean;

  /**
   * Response returned by the target character. This may be empty depending on
   * character settings. Client must handle for each case.
   *
   * @generated from field: string text = 4;
   */
  text: string;

  /**
   * Indicates what was filtered based on workspace settings. Assume empty if
   * the input was moderated.
   *
   * @generated from field: repeated spawner.input_filter.v1.InputFilterMatch matches = 5;
   */
  matches: InputFilterMatch[];
};

/**
 * Describes the message spawner.input_filter.v1.InputFilterEvent.
 * Use `create(InputFilterEventSchema)` to create a new message.
 */
export const InputFilterEventSchema: GenMessage<InputFilterEvent> = /*@__PURE__*/
  messageDesc(file_spawner_input_filter_v1_input_filter, 1);

/**
 * @generated from enum spawner.input_filter.v1.InputFilterType
 */
export enum InputFilterType {
  /**
   * @generated from enum value: INPUT_FILTER_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: INPUT_FILTER_TYPE_MODERATION = 1;
   */
  MODERATION = 1,

  /**
   * @generated from enum value: INPUT_FILTER_TYPE_CUSTOM = 2;
   */
  CUSTOM = 2,
}

/**
 * Describes the enum spawner.input_filter.v1.InputFilterType.
 */
export const InputFilterTypeSchema: GenEnum<InputFilterType> = /*@__PURE__*/
  enumDesc(file_spawner_input_filter_v1_input_filter, 0);

