// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/core/v1/core.proto (package spawner.core.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { CoreSearchSchema } from "../../core_components/search/v1/search_pb";
import { file_spawner_core_components_search_v1_search } from "../../core_components/search/v1/search_pb";

/**
 * Describes the file spawner/core/v1/core.proto.
 */
export const file_spawner_core_v1_core: GenFile = /*@__PURE__*/
  fileDesc("ChpzcGF3bmVyL2NvcmUvdjEvY29yZS5wcm90bxIPc3Bhd25lci5jb3JlLnYxMnUKC0NvcmVTZXJ2aWNlEmYKBlNlYXJjaBItLnNwYXduZXIuY29yZV9jb21wb25lbnRzLnNlYXJjaC52MS5Db3JlU2VhcmNoGi0uc3Bhd25lci5jb3JlX2NvbXBvbmVudHMuc2VhcmNoLnYxLkNvcmVTZWFyY2hCfgoTY29tLnNwYXduZXIuY29yZS52MUIJQ29yZVByb3RvUAGiAgNTQ1iqAg9TcGF3bmVyLkNvcmUuVjHKAg9TcGF3bmVyXENvcmVcVjHiAhtTcGF3bmVyXENvcmVcVjFcR1BCTWV0YWRhdGHqAhFTcGF3bmVyOjpDb3JlOjpWMWIGcHJvdG8z", [file_spawner_core_components_search_v1_search]);

/**
 * @generated from service spawner.core.v1.CoreService
 */
export const CoreService: GenService<{
  /**
   * @generated from rpc spawner.core.v1.CoreService.Search
   */
  search: {
    methodKind: "unary";
    input: typeof CoreSearchSchema;
    output: typeof CoreSearchSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_spawner_core_v1_core, 0);

