// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/packet_components/perception/v1/perception.proto (package spawner.packet_components.perception.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { EnvironmentEvent } from "../../environment/v1/environment_pb";
import { file_spawner_packet_components_environment_v1_environment } from "../../environment/v1/environment_pb";
import type { ObservationEvent } from "../../observation/v1/observation_pb";
import { file_spawner_packet_components_observation_v1_observation } from "../../observation/v1/observation_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/packet_components/perception/v1/perception.proto.
 */
export const file_spawner_packet_components_perception_v1_perception: GenFile = /*@__PURE__*/
  fileDesc("CjhzcGF3bmVyL3BhY2tldF9jb21wb25lbnRzL3BlcmNlcHRpb24vdjEvcGVyY2VwdGlvbi5wcm90bxInc3Bhd25lci5wYWNrZXRfY29tcG9uZW50cy5wZXJjZXB0aW9uLnYxIqQCCg9QZXJjZXB0aW9uRXZlbnQSSgoEdHlwZRgBIAEoDjI8LnNwYXduZXIucGFja2V0X2NvbXBvbmVudHMucGVyY2VwdGlvbi52MS5QZXJjZXB0aW9uRXZlbnRUeXBlEhQKCGFnZW50X2lkGAIgASgJQgIYARJRCgtvYnNlcnZhdGlvbhgDIAEoCzI6LnNwYXduZXIucGFja2V0X2NvbXBvbmVudHMub2JzZXJ2YXRpb24udjEuT2JzZXJ2YXRpb25FdmVudEgAElEKC2Vudmlyb25tZW50GAQgASgLMjouc3Bhd25lci5wYWNrZXRfY29tcG9uZW50cy5lbnZpcm9ubWVudC52MS5FbnZpcm9ubWVudEV2ZW50SABCCQoHcGF5bG9hZCqKAQoTUGVyY2VwdGlvbkV2ZW50VHlwZRIlCiFQRVJDRVBUSU9OX0VWRU5UX1RZUEVfVU5TUEVDSUZJRUQQABIlCiFQRVJDRVBUSU9OX0VWRU5UX1RZUEVfT0JTRVJWQVRJT04QARIlCiFQRVJDRVBUSU9OX0VWRU5UX1RZUEVfRU5WSVJPTk1FTlQQAkL5AQorY29tLnNwYXduZXIucGFja2V0X2NvbXBvbmVudHMucGVyY2VwdGlvbi52MUIPUGVyY2VwdGlvblByb3RvUAGiAgNTUFCqAiZTcGF3bmVyLlBhY2tldENvbXBvbmVudHMuUGVyY2VwdGlvbi5WMcoCJlNwYXduZXJcUGFja2V0Q29tcG9uZW50c1xQZXJjZXB0aW9uXFYx4gIyU3Bhd25lclxQYWNrZXRDb21wb25lbnRzXFBlcmNlcHRpb25cVjFcR1BCTWV0YWRhdGHqAilTcGF3bmVyOjpQYWNrZXRDb21wb25lbnRzOjpQZXJjZXB0aW9uOjpWMWIGcHJvdG8z", [file_spawner_packet_components_environment_v1_environment, file_spawner_packet_components_observation_v1_observation]);

/**
 * @generated from message spawner.packet_components.perception.v1.PerceptionEvent
 */
export type PerceptionEvent = Message<"spawner.packet_components.perception.v1.PerceptionEvent"> & {
  /**
   * @generated from field: spawner.packet_components.perception.v1.PerceptionEventType type = 1;
   */
  type: PerceptionEventType;

  /**
   * @generated from field: string agent_id = 2 [deprecated = true];
   * @deprecated
   */
  agentId: string;

  /**
   * @generated from oneof spawner.packet_components.perception.v1.PerceptionEvent.payload
   */
  payload: {
    /**
     * @generated from field: spawner.packet_components.observation.v1.ObservationEvent observation = 3;
     */
    value: ObservationEvent;
    case: "observation";
  } | {
    /**
     * @generated from field: spawner.packet_components.environment.v1.EnvironmentEvent environment = 4;
     */
    value: EnvironmentEvent;
    case: "environment";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message spawner.packet_components.perception.v1.PerceptionEvent.
 * Use `create(PerceptionEventSchema)` to create a new message.
 */
export const PerceptionEventSchema: GenMessage<PerceptionEvent> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_perception_v1_perception, 0);

/**
 * @generated from enum spawner.packet_components.perception.v1.PerceptionEventType
 */
export enum PerceptionEventType {
  /**
   * @generated from enum value: PERCEPTION_EVENT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Observations can be interpreted as the agent's memory. The agent may
   * receive observations from the client, as well as automatically through
   * reflections and conversations. Observations are generally long-lived. They
   * may be searched and retrieved by other events (such as chat).
   *
   * @generated from enum value: PERCEPTION_EVENT_TYPE_OBSERVATION = 1;
   */
  OBSERVATION = 1,

  /**
   * Environments allow agents to understand its surrounding. Environements are
   * relatively ephermal and may be updated frequently.
   *
   * @generated from enum value: PERCEPTION_EVENT_TYPE_ENVIRONMENT = 2;
   */
  ENVIRONMENT = 2,
}

/**
 * Describes the enum spawner.packet_components.perception.v1.PerceptionEventType.
 */
export const PerceptionEventTypeSchema: GenEnum<PerceptionEventType> = /*@__PURE__*/
  enumDesc(file_spawner_packet_components_perception_v1_perception, 0);

