// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/packet_components/sentiment/v1/sentiment.proto (package spawner.packet_components.sentiment.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/packet_components/sentiment/v1/sentiment.proto.
 */
export const file_spawner_packet_components_sentiment_v1_sentiment: GenFile = /*@__PURE__*/
  fileDesc("CjZzcGF3bmVyL3BhY2tldF9jb21wb25lbnRzL3NlbnRpbWVudC92MS9zZW50aW1lbnQucHJvdG8SJnNwYXduZXIucGFja2V0X2NvbXBvbmVudHMuc2VudGltZW50LnYxIn4KDlNlbnRpbWVudEV2ZW50EhQKDHV0dGVyYW5jZV9pZBgBIAEoCRJHCgZyZXN1bHQYAiABKA4yNy5zcGF3bmVyLnBhY2tldF9jb21wb25lbnRzLnNlbnRpbWVudC52MS5TZW50aW1lbnRSZXN1bHQSDQoFc2NvcmUYAyABKBEqjwEKD1NlbnRpbWVudFJlc3VsdBIgChxTRU5USU1FTlRfUkVTVUxUX1VOU1BFQ0lGSUVEEAASHAoYU0VOVElNRU5UX1JFU1VMVF9ORVVUUkFMEAESHQoZU0VOVElNRU5UX1JFU1VMVF9QT1NJVElWRRACEh0KGVNFTlRJTUVOVF9SRVNVTFRfTkVHQVRJVkUQA0LzAQoqY29tLnNwYXduZXIucGFja2V0X2NvbXBvbmVudHMuc2VudGltZW50LnYxQg5TZW50aW1lbnRQcm90b1ABogIDU1BTqgIlU3Bhd25lci5QYWNrZXRDb21wb25lbnRzLlNlbnRpbWVudC5WMcoCJVNwYXduZXJcUGFja2V0Q29tcG9uZW50c1xTZW50aW1lbnRcVjHiAjFTcGF3bmVyXFBhY2tldENvbXBvbmVudHNcU2VudGltZW50XFYxXEdQQk1ldGFkYXRh6gIoU3Bhd25lcjo6UGFja2V0Q29tcG9uZW50czo6U2VudGltZW50OjpWMWIGcHJvdG8z");

/**
 * Output only. Indicates the sentiment detection results.
 *
 * @generated from message spawner.packet_components.sentiment.v1.SentimentEvent
 */
export type SentimentEvent = Message<"spawner.packet_components.sentiment.v1.SentimentEvent"> & {
  /**
   * Identifies a grouping of multiple packages.
   *
   * @generated from field: string utterance_id = 1;
   */
  utteranceId: string;

  /**
   * Sentiment detected for the utterance.
   *
   * @generated from field: spawner.packet_components.sentiment.v1.SentimentResult result = 2;
   */
  result: SentimentResult;

  /**
   * Sentiment score takes a value between -2 and +2.
   *
   * -2: strong negative sentiment
   * -1: moderate negative sentiment
   *  0: neutral
   * +1: moderate positive sentiment
   * +2: strong positive sentiment
   *
   *
   * @generated from field: sint32 score = 3;
   */
  score: number;
};

/**
 * Describes the message spawner.packet_components.sentiment.v1.SentimentEvent.
 * Use `create(SentimentEventSchema)` to create a new message.
 */
export const SentimentEventSchema: GenMessage<SentimentEvent> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_sentiment_v1_sentiment, 0);

/**
 * @generated from enum spawner.packet_components.sentiment.v1.SentimentResult
 */
export enum SentimentResult {
  /**
   * @generated from enum value: SENTIMENT_RESULT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SENTIMENT_RESULT_NEUTRAL = 1;
   */
  NEUTRAL = 1,

  /**
   * @generated from enum value: SENTIMENT_RESULT_POSITIVE = 2;
   */
  POSITIVE = 2,

  /**
   * @generated from enum value: SENTIMENT_RESULT_NEGATIVE = 3;
   */
  NEGATIVE = 3,
}

/**
 * Describes the enum spawner.packet_components.sentiment.v1.SentimentResult.
 */
export const SentimentResultSchema: GenEnum<SentimentResult> = /*@__PURE__*/
  enumDesc(file_spawner_packet_components_sentiment_v1_sentiment, 0);

