// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file spawner/packet_components/interpretation/v1/interpretation.proto (package spawner.packet_components.interpretation.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/packet_components/interpretation/v1/interpretation.proto.
 */
export const file_spawner_packet_components_interpretation_v1_interpretation: GenFile = /*@__PURE__*/
  fileDesc("CkBzcGF3bmVyL3BhY2tldF9jb21wb25lbnRzL2ludGVycHJldGF0aW9uL3YxL2ludGVycHJldGF0aW9uLnByb3RvEitzcGF3bmVyLnBhY2tldF9jb21wb25lbnRzLmludGVycHJldGF0aW9uLnYxImMKG0ludGVycHJldGF0aW9uQ29uZmlndXJhdGlvbhIOCgZyZWFzb24YASABKAISDwoHZW1vdGlvbhgCIAEoAhIQCghpbnN0aW5jdBgDIAEoAhIRCgl3aWxscG93ZXIYBCABKAIi3QEKDkludGVycHJldGF0aW9uEk0KBHR5cGUYASABKA4yPy5zcGF3bmVyLnBhY2tldF9jb21wb25lbnRzLmludGVycHJldGF0aW9uLnYxLkludGVycHJldGF0aW9uVHlwZRJuChxpbnRlcnByZXRhdGlvbl9jb25maWd1cmF0aW9uGAIgASgLMkguc3Bhd25lci5wYWNrZXRfY29tcG9uZW50cy5pbnRlcnByZXRhdGlvbi52MS5JbnRlcnByZXRhdGlvbkNvbmZpZ3VyYXRpb24SDAoEdGV4dBgDIAEoCSq/AQoSSW50ZXJwcmV0YXRpb25UeXBlEiMKH0lOVEVSUFJFVEFUSU9OX1RZUEVfVU5TUEVDSUZJRUQQABIeChpJTlRFUlBSRVRBVElPTl9UWVBFX1JFQVNPThABEh8KG0lOVEVSUFJFVEFUSU9OX1RZUEVfRU1PVElPThACEiAKHElOVEVSUFJFVEFUSU9OX1RZUEVfSU5TVElOQ1QQAxIhCh1JTlRFUlBSRVRBVElPTl9UWVBFX1dJTExQT1dFUhAEQpECCi9jb20uc3Bhd25lci5wYWNrZXRfY29tcG9uZW50cy5pbnRlcnByZXRhdGlvbi52MUITSW50ZXJwcmV0YXRpb25Qcm90b1ABogIDU1BJqgIqU3Bhd25lci5QYWNrZXRDb21wb25lbnRzLkludGVycHJldGF0aW9uLlYxygIqU3Bhd25lclxQYWNrZXRDb21wb25lbnRzXEludGVycHJldGF0aW9uXFYx4gI2U3Bhd25lclxQYWNrZXRDb21wb25lbnRzXEludGVycHJldGF0aW9uXFYxXEdQQk1ldGFkYXRh6gItU3Bhd25lcjo6UGFja2V0Q29tcG9uZW50czo6SW50ZXJwcmV0YXRpb246OlYxYgZwcm90bzM");

/**
 * Configures tendencies of the agent's interpretations. Values take a value
 * between 0.0 and 1.0, which represent the likihood of the agent interpreting
 * inputs in certain ways.
 *
 * @generated from message spawner.packet_components.interpretation.v1.InterpretationConfiguration
 */
export type InterpretationConfiguration = Message<"spawner.packet_components.interpretation.v1.InterpretationConfiguration"> & {
  /**
   * @generated from field: float reason = 1;
   */
  reason: number;

  /**
   * @generated from field: float emotion = 2;
   */
  emotion: number;

  /**
   * @generated from field: float instinct = 3;
   */
  instinct: number;

  /**
   * @generated from field: float willpower = 4;
   */
  willpower: number;
};

/**
 * Describes the message spawner.packet_components.interpretation.v1.InterpretationConfiguration.
 * Use `create(InterpretationConfigurationSchema)` to create a new message.
 */
export const InterpretationConfigurationSchema: GenMessage<InterpretationConfiguration> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_interpretation_v1_interpretation, 0);

/**
 * @generated from message spawner.packet_components.interpretation.v1.Interpretation
 */
export type Interpretation = Message<"spawner.packet_components.interpretation.v1.Interpretation"> & {
  /**
   * @generated from field: spawner.packet_components.interpretation.v1.InterpretationType type = 1;
   */
  type: InterpretationType;

  /**
   * Only input. Configure the interpretation of the agent. Configuration may be
   * changed at runtime. (e.g. Change how the agent interprets events depending
   * on in-game state.)
   *
   * @generated from field: spawner.packet_components.interpretation.v1.InterpretationConfiguration interpretation_configuration = 2;
   */
  interpretationConfiguration?: InterpretationConfiguration;

  /**
   * Only output. Represents the result of the interpretation made by the agent.
   *
   * @generated from field: string text = 3;
   */
  text: string;
};

/**
 * Describes the message spawner.packet_components.interpretation.v1.Interpretation.
 * Use `create(InterpretationSchema)` to create a new message.
 */
export const InterpretationSchema: GenMessage<Interpretation> = /*@__PURE__*/
  messageDesc(file_spawner_packet_components_interpretation_v1_interpretation, 1);

/**
 * @generated from enum spawner.packet_components.interpretation.v1.InterpretationType
 */
export enum InterpretationType {
  /**
   * @generated from enum value: INTERPRETATION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: INTERPRETATION_TYPE_REASON = 1;
   */
  REASON = 1,

  /**
   * @generated from enum value: INTERPRETATION_TYPE_EMOTION = 2;
   */
  EMOTION = 2,

  /**
   * @generated from enum value: INTERPRETATION_TYPE_INSTINCT = 3;
   */
  INSTINCT = 3,

  /**
   * @generated from enum value: INTERPRETATION_TYPE_WILLPOWER = 4;
   */
  WILLPOWER = 4,
}

/**
 * Describes the enum spawner.packet_components.interpretation.v1.InterpretationType.
 */
export const InterpretationTypeSchema: GenEnum<InterpretationType> = /*@__PURE__*/
  enumDesc(file_spawner_packet_components_interpretation_v1_interpretation, 0);

